apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-logs-pv
  namespace: default
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: "/tmp/data"