apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-logs-pvc-2
  namespace: default
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi